#10 CI failing on shellcheck

diff --git a/create-lx-image b/create-lx-image
--- a/create-lx-image
+++ b/create-lx-image
@@ -4,6 +4,7 @@
 #
 # Create an lx-brand image from a given tar file
 
+# shellcheck disable=2154
 if [[ -n "$TRACE" ]]; then
   export PS4='[\D{%FT%TZ}] ${BASH_SOURCE}:${LINENO}: ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
   set -o xtrace
@@ -49,7 +50,7 @@ do
 	case $OPTION in
 		h)
 			usage
-			exit 1
+			exit
 			;;
 		t)
 			TARBALL=${OPTARG}
@@ -69,9 +70,9 @@ do
 		u)
 			DOCS=${OPTARG}
 			;;
-		?)
+		*)
 			usage
-			exit
+			exit 1
 			;;
 	esac
 done
@@ -83,17 +84,17 @@ if [[ -z $TARBALL ]]; then
 fi
 
 if [[ ! -a "$TARBALL" ]]; then
-	printf "==> ERROR: %s: file or directory not found\n" $TARBALL
+	printf "==> ERROR: %s: file or directory not found\n" "$TARBALL"
 	exit 1
 fi
 
-if [[ "$(echo $TARBALL | cut -c 1)" != "/" ]]; then
-	printf "==> Pathname '%s' specified to -t must be absolute\n" $TARBALL
+if [[ "$(echo "$TARBALL" | cut -c 1)" != "/" ]]; then
+	printf "==> Pathname '%s' specified to -t must be absolute\n" "$TARBALL"
 	exit 1
 fi
 
 if [[ ! -r "$TARBALL" ]]; then
-	printf "==> Cannot read file '%s'\n" $TARBALL
+	printf "==> Cannot read file '%s'\n" "$TARBALL"
 	exit 1
 fi
 
@@ -128,7 +129,7 @@ fi
 
 IUUID=${IMAGE_NAME}-$BUILD_DATE
 
-filetype=$({ LC_ALL=C file $TARBALL | awk '{print $2}' ; } 2>/dev/null)
+filetype=$({ LC_ALL=C file "$TARBALL" | awk '{print $2}' ; } 2>/dev/null)
 
 if [[ "$filetype" = "gzip" ]]; then
 	gtaropts="-xz"
@@ -150,14 +151,14 @@ zroot="/zones/$IUUID/root"
 
 create_dataset() {
 	echo "==> Creating dataset for image creation..."
-	zfs create zones/$IUUID
-	chmod 700 $zpath
+	zfs create "zones/$IUUID"
+	chmod 700 "$zpath"
 
-	mkdir $zpath/root
-	chmod 755 $zpath/root
+	mkdir "$zpath/root"
+	chmod 755 "$zpath/root"
 
-	mkdir $zpath/cores
-	chmod 755 $zpath/cores
+	mkdir "$zpath/cores"
+	chmod 755 "$zpath/cores"
 
 	echo "==> The dataset is zones/$IUUID"
 	echo "==>"
@@ -165,10 +166,9 @@ create_dataset() {
 
 install_tar() {
 	echo "==> Installing the tar archive, this will take a few minutes..."
-	( cd "$zroot" && gtar --strip-components=2 "$gtaropts" "$TARBALL" )
-	if [[ "$?" -ne "0" ]] ; then
+	if ! (cd "$zroot" && gtar --strip-components=2 "$gtaropts" "$TARBALL"); then
 		echo "==> Error: extraction from tar archive failed."
-		zfs destroy -r zones/$IUUID
+		zfs destroy -r "zones/$IUUID"
 	fi
 }
 
@@ -176,25 +176,24 @@ modify_image() {
 	echo "==> Modifying the image to work in a zone..."
 
 	echo "====> Creating /native directories..."
-	mkdir -p $zroot/native/dev
-	mkdir -p $zroot/native/etc/default
-	mkdir -p $zroot/native/etc/svc/volatile
-	mkdir -p $zroot/native/lib
-	mkdir -p $zroot/native/proc
-	mkdir -p $zroot/native/tmp
-	chmod 1777 $zroot/native/tmp
-	mkdir -p $zroot/native/usr
-	mkdir -p $zroot/native/var
+	mkdir -p "$zroot/native/dev"
+	mkdir -p "$zroot/native/etc/default"
+	mkdir -p "$zroot/native/etc/svc/volatile"
+	mkdir -p "$zroot/native/lib"
+	mkdir -p "$zroot/native/proc"
+	mkdir -p "$zroot/native/tmp"
+	chmod 1777 "$zroot/native/tmp"
+	mkdir -p "$zroot/native/usr"
+	mkdir -p "$zroot/native/var"
 	echo "====> done."
 
 	# Create the /var/ld/ld.config files that will point to /native/lib for our
 	# Solaris libraries.
 
 	echo "====> Creating the /var/ld/ld.config file..."
-	mkdir $zroot/var/ld
-	mkdir $zroot/var/ld/64
+	mkdir "$zroot/var/ld" "$zroot/var/ld/64"
 
-if crle -c $zroot/var/ld/ld.config -l /native/lib:/native/usr/lib \
+if crle -c "$zroot/var/ld/ld.config" -l /native/lib:/native/usr/lib \
 	-s /native/lib/secure:/native/usr/lib/secure ; then
 	echo "====> Created \"$zroot/var/ld/ld.config\""
 else
@@ -202,7 +201,7 @@ else
 	exit 1
 fi
 
-if crle -64 -c $zroot/var/ld/64/ld.config \
+if crle -64 -c "$zroot/var/ld/64/ld.config" \
 	-l /native/lib/amd64:/native/usr/lib/amd64 \
 	-s /native/lib/secure/amd64:/native/usr/lib/secure/amd64 ; then
 	echo "====> Created \"$zroot/var/ld/64/ld.config\""
@@ -212,7 +211,7 @@ else
 fi
 
 	echo "====> Setting up fstab..."
-cat << EOF > $zroot/etc/fstab
+cat << EOF > "$zroot/etc/fstab"
 none		/			zfs	defaults	1 1
 proc		/proc			proc	defaults	0 0
 EOF
@@ -224,14 +223,14 @@ create_file() {
 	echo "==> Creating image file:"
 
 	echo "====> Creating snapshot..."
-	zfs snapshot zones/$IUUID@final
+	zfs snapshot "zones/$IUUID@final"
 
 	echo "====> Doing a zfs send. This may take a few minutes..."
-	zfs send zones/$IUUID@final | gzip -9 > ${IMAGE_NAME}-${BUILD_DATE}.zfs.gz
+	zfs send "zones/$IUUID@final" | gzip -9 > "${IMAGE_NAME}-${BUILD_DATE}.zfs.gz"
 	echo "====> Done."
 
 	echo "====> Cleaning up..."
-	zfs destroy -r zones/$IUUID
+	zfs destroy -r "zones/$IUUID"
 
 	echo "==> Image File created!"
 	echo "==>"
@@ -239,7 +238,7 @@ create_file() {
 
 create_manifest() {
 	echo "==> Creating manifest file..."
-	./create-manifest -f ${IMAGE_NAME}-${BUILD_DATE}.zfs.gz -k ${KERNEL} -m ${MIN_PLATFORM} -n ${IMAGE_NAME} -o linux -v ${BUILD_DATE} -d ${DESC} -h ${DOCS} > ${IMAGE_NAME}-${BUILD_DATE}.json
+	./create-manifest -f "${IMAGE_NAME}-${BUILD_DATE}.zfs.gz" -k "${KERNEL}" -m "${MIN_PLATFORM}" -n "${IMAGE_NAME}" -o linux -v "${BUILD_DATE}" -d "${DESC}" -h "${DOCS}" > "${IMAGE_NAME}-${BUILD_DATE}.json"
 	echo "==> done!"
 	echo "==>"
 }
