Better output, different approach to crle command

diff --git a/create-lx-image b/create-lx-image
--- a/create-lx-image
+++ b/create-lx-image
@@ -41,28 +41,28 @@ done
 
 
 if [[ -z $tarball ]]; then
-	echo "ERROR: the install archive is required"
+	echo "==> ERROR: the install archive is required"
 	usage
   exit 1
 fi
 
 if [[ ! -a "$tarball" ]]; then
-	printf "ERROR: %s: file or directory not found\n" $tarball
+	printf "==> ERROR: %s: file or directory not found\n" $tarball
 	exit 1
 fi
 
 if [[ "$(echo $tarball | cut -c 1)" != "/" ]]; then
-	printf "Pathname '%s' specified to -t must be absolute\n" $tarball
+	printf "==> Pathname '%s' specified to -t must be absolute\n" $tarball
 	exit 1
 fi
 
 if [[ ! -r "$tarball" ]]; then
-	printf "Cannot read file '%s'\n" $tarball
+	printf "==> Cannot read file '%s'\n" $tarball
 	exit 1
 fi
 
 if [[ ! -f "$tarball" ]]; then
-	echo "ERROR: must be a gzip, bzip2, .Z or uncompressed tar archive"
+	echo "==> ERROR: must be a gzip, bzip2, .Z or uncompressed tar archive"
 	exit 1
 fi
 
@@ -77,7 +77,7 @@ elif [[ "$filetype" = "compressed" ]]; then
 elif [[ "$filetype" = "USTAR" ]]; then
 	gtaropts="-x"
 else
-	printf "ERROR: must be a gzip, bzip2, .Z or uncompressed tar archive"
+	printf "==> ERROR: must be a gzip, bzip2, .Z or uncompressed tar archive"
 	exit 1
 fi
 
@@ -97,7 +97,7 @@ function create_dataset {
   mkdir $zpath/cores
   chmod 755 $zpath/cores
 
-  echo "==> the dataset is zones/$iuuid"
+  echo "==> The dataset is zones/$iuuid"
   echo "==>"
 }
 
@@ -113,6 +113,7 @@ function install_tar {
 function modify_image {
   echo "==> Modifying the image to work in a zone..."
 
+  echo "====> Creating /native directories..."
   mkdir -p $zroot/native/dev
   mkdir -p $zroot/native/etc/default
   mkdir -p $zroot/native/etc/svc/volatile
@@ -122,37 +123,55 @@ function modify_image {
   chmod 1777 $zroot/native/tmp
   mkdir -p $zroot/native/usr
   mkdir -p $zroot/native/var
+  echo "====> done."
   
   # Create the /var/ld/ld.config files that will point to /native/lib for our
   # Solaris libraries.
+  
+  echo "====> Creating the /var/ld/ld.config file..."
   mkdir $zroot/var/ld
   mkdir $zroot/var/ld/64
 
-  if ! crle -c $zroot/var/ld/ld.config -l /native/lib:/native/usr/lib \
-       -s /native/lib/secure:/native/usr/lib/secure; then
-  	echo "Creation of \"$zroot/var/ld/ld.config\" failed!"
-  	exit 1
-  fi
+if crle -c $zroot/var/ld/ld.config -l /native/lib:/native/usr/lib \
+  -s /native/lib/secure:/native/usr/lib/secure ; then
+  echo "====> Created \"$zroot/var/ld/ld.config\""
+else
+  echo "====> Creation of \"$zroot/var/ld/ld.config\" failed!"
+  exit 1
+fi
 
-  if ! crle -64 -c $zroot/var/ld/64/ld.config \
-       -l /native/lib/amd64:/native/usr/lib/amd64 \
-       -s /native/lib/secure/amd64:/native/usr/lib/secure/amd64; then
-  	echo "Creation of \"$zroot/var/ld/64/ld.config\" failed!"
-  	exit 1
-  fi
+if crle -64 -c $zroot/var/ld/64/ld.config \
+  -l /native/lib/amd64:/native/usr/lib/amd64 \
+  -s /native/lib/secure/amd64:/native/usr/lib/secure/amd64 ; then
+  echo "====> Created \"$zroot/var/ld/64/ld.config\""  
+else
+  echo "====> Creation of \"$zroot/var/ld/64/ld.config\" failed!"
+  exit 1
+fi
 
+  echo "====> Setting up fstab..."
   cat > $zroot/etc/fstab <<- EOF
   	none		/			zfs	defaults	1 1
   	proc		/proc			proc	defaults	0 0
   EOF
+  
+  echo "==> Image modification complete."
 }
 
 function create_file {
-  echo "==> Creating image file..."
+  echo "==> Creating image file:"
+  
+  echo "====> Creating snapshot..."
   zfs snapshot zones/$iuuid@final
+  
+  echo "====> Doing a zfs send. This may take a few minutes..."
   zfs send zones/$iuuid@final | gzip -9 > ${IMAGE_NAME}-${BUILD_DATE}.zfs.gz
+  echo "====> Done."
+  
+  echo "====> Cleaning up..."
   zfs destroy -r zones/$iuuid
-  echo "==> done!"
+  
+  echo "==> Image File created!"
   echo "==>"
 }
 
