Check for missing flag arguments

diff --git a/install b/install
--- a/install
+++ b/install
@@ -76,6 +76,25 @@ if [[ ! -e "$INSTALL_DIR" ]] ; then
   echo "Directory $INSTALL_DIR not found"
   exit 1
 fi
+if [[ -z ${INSTALL_DIR} ]]; then
+  echo "Error: missing install directory (-d) value"
+  exit 1
+fi
+
+if [[ -z ${MIRROR} ]]; then
+  echo "Error: missing mirror (-m) value"
+  exit 1
+fi
+
+if [[ -z ${IMAGE_NAME} ]]; then
+  echo "Error: missing image name (-i) value"
+  exit 1
+fi
+
+if [[ -z ${NAME} ]]; then
+  echo "Error: missing proper name (-p) value"
+  exit 1
+fi
 
 TARGET="${IMAGE_NAME}-${BUILD_DATE}.tar.gz"
 
