Add option for specifying RELEASE_PACKAGE
This will make it to install other releases of CentOS 6 or 7

diff --git a/install b/install
--- a/install
+++ b/install
@@ -8,7 +8,6 @@
 set -euo pipefail
 IFS=$'\n\t'
 
-PACKAGE=centos-release-6-6.el6.centos.12.2.x86_64.rpm
 GUESTTOOLS=guesttools
 BUILD_DATE=$(date +%Y%m%d)
 
@@ -18,14 +17,15 @@ cat <<EOF
 Install and modify CentOS in a given directory in a given directory using a given mirror
 
 Usage:
-  $0 -d <INSTALL_DIR> -m <MIRROR> -i <IMAGE_NAME> -p <NAME> -D <DESC> -u <DOCS>
+  $0 -d <INSTALL_DIR> -m <MIRROR> -r <RELEASE_PACKAGE> -i <IMAGE_NAME> -p <NAME> -D <DESC> -u <DOCS>
 
 Example:
-  $0 -d /data/chroot -m http://mirror.centos.org/centos/6/os/x86_64/Packages -i lx-centos-6 -p "CentOS 6.6 LX Brand" -D "CentOS 6.6 64-bit lx-brand image." -u https://docs.joyent.com/images/lx-brand-beta
+  $0 -d /data/chroot -m http://mirror.centos.org/centos/6/os/x86_64/Packages -r centos-release-6-6.el6.centos.12.2.x86_64.rpm -i lx-centos-6 -p "CentOS 6.6 LX Brand" -D "CentOS 6.6 64-bit lx-brand image." -u https://docs.joyent.com/images/lx-brand-beta
 
 OPTIONS:
   -d A path to the install directory
   -m A URL for the desired archive mirror
+  -r The release package used for installing CentOS
   -i The name of the image. This is used for naming the tarball. 
   -p The proper name of the image. Use quotes. This is used in the MOTD and /etc/product file.
   -D A description for the image. This is used in the image manifest and the /etc/product file.
@@ -37,12 +37,13 @@ EOF
 
 INSTALL_DIR=
 MIRROR=
+RELEASE_PACKAGE=
 IMAGE_NAME=
 NAME=
 DESC=
 DOCS=
 
-while getopts "hd:m:i:p:D:u:" OPTION
+while getopts "hd:m:r:i:p:D:u:" OPTION
 do
   case $OPTION in
     h)
@@ -54,6 +55,9 @@ do
       ;;
     m)
       MIRROR=${OPTARG}
+      ;;
+    r)
+      RELEASE_PACKAGE=${OPTARG}
       ;;
     i)
       IMAGE_NAME=${OPTARG}
@@ -94,6 +98,11 @@ if [[ -z ${MIRROR} ]]; then
   exit 1
 fi
 
+if [[ -z ${RELEASE_PACKAGE} ]]; then
+  echo "Error: missing release package (-r) value"
+  exit 1
+fi
+
 if [[ -z ${IMAGE_NAME} ]]; then
   echo "Error: missing image name (-i) value"
   exit 1
@@ -127,13 +136,13 @@ fi
 rpm --rebuilddb --root=$INSTALL_DIR
 
 echo "==> Getting CentOS 6.6 rpm..."
-wget -O /var/tmp/$PACKAGE $MIRROR/$PACKAGE
+wget -O /var/tmp/$RELEASE_PACKAGE $MIRROR/$RELEASE_PACKAGE
 
-echo "==> Veryfying CentOS 6.6 rpm..."
-rpm -K /var/tmp/$PACKAGE
+echo "==> Veryfying $RELEASE_PACKAGE..."
+rpm -K /var/tmp/$RELEASE_PACKAGE
 
 echo "==> Installing rpm package..."
-rpm -i --root=$INSTALL_DIR --nodeps /var/tmp/$PACKAGE
+rpm -i --root=$INSTALL_DIR --nodeps /var/tmp/$RELEASE_PACKAGE
 
 echo "==> Installing @core packages..."
 yum --installroot=$INSTALL_DIR --setopt=tsflags=nodocs \
@@ -145,8 +154,8 @@ yum --installroot=$INSTALL_DIR --setopt=tsflags=nodocs install -y less man opens
 echo "==> Cleaning up yum cache..."
 yum --installroot=$INSTALL_DIR clean all
 
-echo "==> Removing /var/tmp/$PACKAGE"
-rm -rf /var/tmp/$PACKAGE
+echo "==> Removing /var/tmp/$RELEASE_PACKAGE"
+rm -rf /var/tmp/$RELEASE_PACKAGE
 
 echo "==> Setting TZ to UTC"
 rm $INSTALL_DIR/etc/localtime
